### ISSUE TITLE
ERROR (MainThread) [homeassistant.components.mqtt.climate] Invalid swing_modes mode: 0

### ISSUE THREAD

**Issue by ArtemVladimirov** [liaan/broadlink_ac_mqtt#108]
The following message appears in the Home Assistant logger

`ERROR (MainThread) [homeassistant.components.mqtt.climate] Invalid swing_modes mode: 0`

My config:

```
mqtt:
      host: 192.168.1.36
      port: 1883
      client_id: ac_to_mqtt
      topic_prefix: /aircon
      auto_discovery_topic: homeassistant
      auto_discovery_topic_retain: true
      discovery: true
```
